networks:
  internal:
    name: "internal"
    # External means the container will be accessible from other containers in the same network.
    # If you want to isolate the container create a new network, with different name for each container and without being external.
    external: true

services:
  mailpit:
    image: "axllent/mailpit:v1.30"
    container_name: "mailpit"
    restart: "unless-stopped"
    networks:
      - "internal"
    ports:
      - "${MAILPIT_SMTP_PORT?Variable not set}:1025"
      - "${MAILPIT_PORT?Variable not set}:8025"
    environment:
      - "MP_SMTP_AUTH_ACCEPT_ANY=${MAILPIT_SMTP_AUTH_ACCEPT_ANY?Variable not set}"
      - "MP_SMTP_AUTH_ALLOW_INSECURE=${MAILPIT_SMTP_AUTH_ALLOW_INSECURE?Variable not set}"
    labels:
      - "traefik.enable=false"
