# TODO: Use Secrets to store the passwords to all containers.
# TODO: Monitor and update to latest version.
# TODO: Add extra performance configuration, using https://pgtune.leopard.in.ua/#/.
version: "3.9"

networks:
  internal:
    name: "internal"
    # External means the container will be accessible from other containers in the same network.
    # If you want to isolate the container create a new network, with different name for each container and without being external.
    external: true

volumes:
  postgresql:
    name: "postgresql"

services:
  postgresql:
    image: "postgres:16"
    container_name: "postgresql"
    restart: "unless-stopped"
    networks:
      - "internal"
    ports:
      - "${POSTGRESQL_PORT?Variable not set}:${POSTGRESQL_PORT?Variable not set}"
    volumes:
      - "postgresql:/var/lib/postgresql/data"
      - "./configuration/postgresql.conf:/etc/postgresql.conf"
    environment:
      - "POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD?Variable not set}"
      - "POSTGRES_USER=${POSTGRESQL_USER?Variable not set}"
      - "POSTGRES_HOST_AUTH_METHOD=${POSTGRESQL_AUTHENTICATION_METHOD?Variable not set}"
    command: "-p ${POSTGRESQL_PORT?Variable not set}"
    labels:
      - "traefik.enable=false"
